[main]
    separator = "-"
    description = "This blog documents every major problem Yash solves."
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "libsass"


[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false

[docs]
    github = "https://github.com/gethinode/hinode"
    release = "https://github.com/gethinode/hinode/releases/tag/"
    checkVersion = false

[home]
    # sections = ["posts", "projects"]
    fullCover = true
    centerHeadline = true
    style = ""

[navigation]
    anchor = true
    logo = "/img/Yash.png"
    logoWidth = 250
    color = "body"
    fixed = true
    offset = "0rem"
    overlay = true
    search = true
    searchModal = true
    breadcrumb = false
    toc = true
    sidebar = true
    size = "sm"

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

# toml-docs-start sections
# [sections]
#     [sections.posts]
#         title = "Posts"
#         sort = "date"
#         reverse = true
#         nested = true
#         cols = 3
#         color = ""
#         padding = "0"
#         header = "full"
#         footer = "none"
#         orientation = "stacked"
#         style = "border-0 card-zoom"
#         homepage = 3
#         separator = true

[sections]
    [sections.blog]
        title = "Blog"
        layout = "card"
        reverse = true
        nested = true
        sort = "date"
        separator = true
    [sections.projects]
        title = "Projects"
        nested = false
        layout = "list"

# toml-docs-end sections

[favicon]
    logo = "img/favicon/YN2.png"
    sizes = [16, 32, 48]

[style]
    primary = "#025db8"
    secondary = "#72acfc"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Junge, Lora, Ubuntu"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Grey+Qo&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem"
    purge = false

[schema]
    type = "Organization"
    name = "Yash Narang"
    locale = "en-US"
    section = "blog"
    [author]
        name = "Yash Narang"
    [logo]
        url = "/img/Yash.png"
        width = 250
        height = 72

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[links]
    hinode = "https://gethinode.com"
