[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20
[[main]]
  name = "About"
  pageRef = "/about"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/yash-narang-7b5806325/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/yashnarang000"
  weight = 20

[[social]]
  name = "Instagram"
  pre = "fab fa-instagram"
  url = "https://www.instagram.com/yashnarang000/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Posts"
  pageRef = "/posts/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation